# version: "3.9"

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   dbeaver:
#     image: dbeaver/cloudbeaver:latest
#     container_name: dbeaver
#     restart: always
#     ports:
#       - "8978:8978"   # Access DBeaver in browser at http://localhost:8978
#     volumes:
#       - dbeaver_data:/opt/cloudbeaver/workspace

# volumes:
#   mysql_data:
#   dbeaver_data:
